# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_tittle', models.CharField(max_length=200)),
                ('article_content', models.TextField()),
                ('article_slug', models.SlugField()),
            ],
        ),
    ]
