# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_slug',
            field=models.SlugField(editable=False),
        ),
    ]
