# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-27 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0002_auto_20180325_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_level_name', models.CharField(max_length=200)),
                ('conversation_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_token', models.CharField(editable=False, max_length=200)),
                ('conversation_name', models.CharField(max_length=200)),
                ('conversation_email', models.CharField(max_length=200)),
                ('conversation_platform', models.CharField(max_length=200)),
                ('conversation_faculty', models.CharField(max_length=200)),
                ('conversation_create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('conversation_update_date', models.DateTimeField(auto_now=True, null=True)),
                ('conversation_conversation_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.ConversationLevels')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_article_name', models.CharField(max_length=200)),
                ('question_article_description', models.TextField()),
                ('question_article_keywords', models.TextField()),
                ('question_article_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_record_create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('question_response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('question_description', models.TextField()),
                ('question_keywords', models.TextField()),
                ('question_conversation_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.ConversationLevels')),
            ],
        ),
        migrations.AddField(
            model_name='questionrecords',
            name='question_record_conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Questions'),
        ),
        migrations.AddField(
            model_name='questionarticles',
            name='question_article_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Questions'),
        ),
    ]
