# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0003_auto_20180327_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionrecords',
            old_name='question_response',
            new_name='question_record_response',
        ),
        migrations.RemoveField(
            model_name='questionarticles',
            name='question_article_article',
        ),
        migrations.AddField(
            model_name='questionrecords',
            name='question_record_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Questions'),
        ),
        migrations.AddField(
            model_name='questionrecords',
            name='question_record_token',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='conversation_conversation_level',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.ConversationLevels'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='conversation_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='conversation_faculty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='conversation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='conversation_platform',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='questionrecords',
            name='question_record_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gti.Conversations'),
        ),
    ]
