# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0005_auto_20180330_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionarticles',
            name='question_article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Category'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Category'),
        ),
    ]
