# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0006_auto_20180330_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_field_update',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_update',
            field=models.BooleanField(default=False),
        ),
    ]
