# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0008_questions_question_replace'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='question_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Category'),
        ),
    ]
