# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0009_articles_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_load_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_load_question',
            field=models.BooleanField(default=False),
        ),
    ]
