# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-22 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0011_auto_20180421_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_platform',
            field=models.BooleanField(default=False),
        ),
    ]
