# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0013_frequentquestions_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent_questions_name', models.CharField(max_length=200)),
                ('frequent_questions_Platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Platform')),
                ('frequent_questions_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='frequentquestions',
            name='frequent_questions_category',
        ),
        migrations.DeleteModel(
            name='FrequentQuestions',
        ),
    ]
