# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-23 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gti', '0014_auto_20180422_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_article_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='article_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_type_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gti.TypeArticle'),
        ),
    ]
